apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: giropops
  labels:
    app: nginx-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 10%
        maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx  
        image: nginx:1.15.0
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "300m"
            memory: "64Mi"
